// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG6ZnH7vu5CQis8enmpRVgAvvQx9fwVtw',
    appId: '1:1090255903778:web:61b6d2ed48db3740fcbe7b',
    messagingSenderId: '1090255903778',
    projectId: 'sehat-mand-pakistan',
    authDomain: 'sehat-mand-pakistan.firebaseapp.com',
    storageBucket: 'sehat-mand-pakistan.firebasestorage.app',
    measurementId: 'G-GV8MTZCPEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkE0CmZod8one27UapO1QSJ1v4nlCk1I',
    appId: '1:1090255903778:android:741a84784c8ce884fcbe7b',
    messagingSenderId: '1090255903778',
    projectId: 'sehat-mand-pakistan',
    storageBucket: 'sehat-mand-pakistan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvx3q5cWBPM0PE4BC7R7NY-EwtDDXpuc0',
    appId: '1:1090255903778:ios:b1c2aa36d6d52386fcbe7b',
    messagingSenderId: '1090255903778',
    projectId: 'sehat-mand-pakistan',
    storageBucket: 'sehat-mand-pakistan.firebasestorage.app',
    iosBundleId: 'com.example.sehatMandPakistan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvx3q5cWBPM0PE4BC7R7NY-EwtDDXpuc0',
    appId: '1:1090255903778:ios:b1c2aa36d6d52386fcbe7b',
    messagingSenderId: '1090255903778',
    projectId: 'sehat-mand-pakistan',
    storageBucket: 'sehat-mand-pakistan.firebasestorage.app',
    iosBundleId: 'com.example.sehatMandPakistan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG6ZnH7vu5CQis8enmpRVgAvvQx9fwVtw',
    appId: '1:1090255903778:web:e825151f896fd7dffcbe7b',
    messagingSenderId: '1090255903778',
    projectId: 'sehat-mand-pakistan',
    authDomain: 'sehat-mand-pakistan.firebaseapp.com',
    storageBucket: 'sehat-mand-pakistan.firebasestorage.app',
    measurementId: 'G-C86FME4WN8',
  );
}
